package handlers

import (
	"math/rand"
)

var listOfEnviorment = []string{"local", "prod", "preprod", "staging", "Dev", "Staging", "Production", "QA", "Test", "Demo", "Local", "Docker", "Kubernetes", "AWS", "Azure", "GCP", "Heroku", "DigitalOcean"}
var fakeEmails = []string{
	"johndoe@gmail.com",
	"janedoe@yahoo.com",
	"marysmith@hotmail.com",
	"michaeljones@aol.com",
	"davidwilliams@msn.com",
	"sarahbrown@icloud.com",
	"peterjohnson@yahoo.com",
	"susanwhite@gmail.com",
	"jamesgreen@hotmail.com",
	"emilythomas@aol.com",
	"williamanderson@msn.com",
	"jessicaclark@icloud.com",
	"roberttaylor@yahoo.com",
	"jenniferwilson@gmail.com",
	"richardmartin@hotmail.com",
	"carolinemiller@aol.com",
	"charlesjackson@msn.com",
	"elizabethevans@icloud.com",
	"danielgonzalez@yahoo.com",
	"amandarodriguez@gmail.com",
	"stevenhernandez@hotmail.com",
	"victoriagarcia@aol.com",
	"christopherlopez@msn.com",
	"nicoleperez@icloud.com",
	"matthewcastillo@yahoo.com",
	"sarahsanchez@gmail.com",
	"anthonygonzalez@hotmail.com",
	"mariahernandez@aol.com",
	"alexanderlopez@msn.com",
	"lauraperez@icloud.com",
	"jacobcastillo@yahoo.com",
	"danielasanchez@gmail.com",
	"angelgonzalez@hotmail.com",
	"jessicahernandez@aol.com",
	"michaellopez@msn.com",
	"ashleyperez@icloud.com",
	"williamcastillo@yahoo.com",
	"emilysanchez@gmail.com",
	"davidgonzalez@hotmail.com",
	"jenniferhernandez@aol.com",
	"johnlopez@msn.com",
	"sarahperez@icloud.com",
	"michaelcastillo@yahoo.com",
	"ashleysanchez@gmail.com",
	"williamgonzalez@hotmail.com",
	"jessicahernandez@aol.com",
	"davidlopez@msn.com",
	"jenniferperez@icloud.com",
	"johncastillo@yahoo.com",
	"sarahsanchez@gmail.com",
	"michaelgonzalez@hotmail.com",
	"ashleyhernandez@aol.com",
	"williamlopez@msn.com",
	"jessicaperez@icloud.com",
	"davidcastillo@yahoo.com",
	"jennifersanchez@gmail.com",
	"johngonzalez@hotmail.com",
	"sarahhernandez@aol.com",
	"michaellopez@msn.com",
	"ashleyperez@icloud.com",
	"williamcastillo@yahoo.com",
	"jessicasanchez@gmail.com",
	"davidgonzalez@hotmail.com",
	"jenniferhernandez@aol.com",
	"johnlopez@msn.com",
	"sarahperez@icloud.com",
	"michaelcastillo@yahoo.com",
	"ashleysanchez@gmail.com",
	"williamgonzalez@hotmail.com",
	"jessicahernandez@aol.com",
	"davidlopez@msn.com",
	"jenniferperez@icloud.com",
	"johncastillo@yahoo.com",
	"sarahsanchez@gmail.com",
	"michaelgonzalez@hotmail.com",
	"ashleyhernandez@aol.com",
	"williamlopez@msn.com",
	"jessicaperez@icloud.com",
	"davidcastillo@yahoo.com",
	"jennifersanchez@gmail.com",
	"johngonzalez@hotmail.com",
	"sarahhernandez@aol.com",
	"michaellopez@msn.com",
	"ashleyperez@icloud.com",
	"williamcastillo@yahoo.com",
}
var fakeSubject = []string{
	"Your account is about to be suspended",
	"Important update about your order",
	"You haveve won a free vacation!",
	"Urgent: Click here to confirm your email address",
	"Your password has been changed",
	"You have 1 new message",
	"New job opportunity",
	"Special offer for you",
	"Don t miss out!",
	"This is important",
	"Act now!",
	"Limited time only",
	"You haveve been invited to join a group",
	"You have a new friend request",
	"Someone has commented on your post",
	"Someone has shared your post",
	"You ve been tagged in a photo",
	"You ve been mentioned in a comment",
	"You ve received a gift",
	"You ve been awarded a badge",
	"You ve reached a new milestone",
	"Congratulations!",
	"Happy birthday!",
	"Merry Christmas!",
	"Happy New Year!",
}

var fakeEmailBodies = []string{
	"Hi, this is John Doe. Im writing to you today to inquire about your services. Im looking for a new email provider, and Ive heard great things about your company. Im particularly interested in your spam filtering capabilities. Can you tell me more about how your spam filter works? Im also interested in your pricing plans. Can you send me a quote? Thanks for your time.",
	"Hello, my name is Jane Doe. Im writing to you today to request a password reset. I recently forgot my password, and Im unable to log into my account. Can you please help me reset my password? Ive attached a copy of my ID to this email for verification purposes. Thank you for your help.",
	"Dear Sir or Madam, I am writing to you today to express my dissatisfaction with your companys product. I recently purchased a new computer from your company, and it has been nothing but problems. The computer has crashed several times, and the customer service department has been unhelpful. I am requesting a full refund for my purchase.",
	"Thank you for your time and consideration. ",
	"Sincerely, John Doe",
	"Subject: New Product Announcement Hi everyone,  Im excited to announce the launch of our new product, the Email Generator. This tool allows you to create fake email bodies in just a few minutes. Simply enter the email address of the recipient, the subject line, and the body of the email, and the Email Generator will create a realistic-looking email for you.",
	"The Email Generator is perfect for a variety of purposes, including:  Testing spam filters Creating marketing campaigns Sending mass emails",
	"The Email Generator is easy to use and free to download. You can find it on our website at www.example.com.  Thanks,",
	"The Team at Example Company",
	"Subject: Account Reminder Hi [Name], This is a reminder that your account with Example Company is due to expire in 30 days. To avoid any interruption in service, please renew your account by clicking on the link below.",
	"[Renew Account Link] If you have any questions, please dont hesitate to contact us. Thank you,",
	"The Team at Example Company",
	"Subject: Important Security Notice 	Hi [Name],",
	"We are writing to inform you of a recent security incident that has affected our systems. As a result of this incident, some of your personal information may have been compromised.",
	"The information that may have been compromised includes your name, email address, and password. We are taking steps to secure your information and prevent further unauthorized access.",
	"If you have any questions or concerns, please dont hesitate to contact us.",
	"Thank you, The Team at Example Company",
	"Subject: New Job Posting  Hi [Name],",
	"We are excited to announce that we are currently hiring for the position of [Position Name]. This is a full-time position with benefits. The ideal candidate will have the following qualifications:",
	"5+ years of experience in [Industry]  Bachelors degree in [Degree]  Strong communication and interpersonal skills Proficient in Microsoft Office Suite If you are interested in this position, please submit your resume and cover letter to [Email Address].",
	"Thank you for your time and consideration.  The Team at Example Company",
	"Subject: Thank You for Your Purchase  Hi [Name],  Thank you for your recent purchase from Example Company. We appreciate your business!",
	"Your order has been shipped and should arrive within 5-7 business days.	If you have any questions, please dont hesitate to contact us.",
	"Thank you again for your purchase!  The Team at Example Company",
	"Subject: Order Confirmation  Hi [Name],  This is to confirm that we have received your order for [Order Number].",
	"Your order will be shipped within 5-7 business days.  You will receive an email with tracking information once your order has shipped.",
	"If you have any questions, please dont hesitate to contact us.  Thank you for your business!  The Team at Example Company",
	"Subject: Invoice Hi [Name],  This is to confirm that we have shipped your order for [Order Number].",
	"Your order total is $[Total].  Please find attached an invoice for your records. If you have any questions, please dont hesitate to contact",
	"Hi, this is John Doe. Im writing to you today to inquire about your product. Im interested in learning more about the features and benefits. Im also interested in getting a quote. Please contact me at your earliest convenience. Thank you for your time.",
	"Hello, this is Jane Doe. Im writing to you today to express my interest in your services. Im looking for a company that can help me with my marketing needs. Im impressed with your companys reputation and Im confident that you can help me achieve my goals. I would like to schedule a meeting to discuss my needs in more detail. Please contact me at your earliest convenience. Thank you for your time.",
	"Good morning, this is Mary Smith. Im writing to you today to thank you for your recent service. I was very impressed with the way you handled my issue. You were professional, efficient, and friendly. I would definitely recommend your company to others. Thank you again for your excellent service.",
	"Good afternoon, this is Michael Jones. Im writing to you today to inquire about your companys pricing. Im interested in learning more about your discounts and promotions. Im also interested in getting a quote for a specific product. Please contact me at your earliest convenience. Thank you for your time.",
	"Good evening, this is David Williams. Im writing to you today to cancel my subscription. Im no longer in need of your services. Please cancel my subscription immediately. Thank you for your time.",
	"Hi, this is Sarah Brown. Im writing to you today to report a problem with your website. Im unable to access the website. Ive tried using different browsers and different devices, but Im still unable to access the website. Please fix the problem as soon as possible. Thank you for your time.",
	"Hello, this is Peter Johnson. Im writing to you today to request a refund. Im not satisfied with the product that I purchased. Ive tried using the product, but it doesnt work as advertised. I would like a full refund. Please contact me at your earliest convenience. Thank you for your time.",
	"Good morning, this is Susan White. Im writing to you today to ask a question. Im not sure how to use your product. Ive read the instructions, but Im still having trouble. I would appreciate it if you could provide me with some help. Please contact me at your earliest convenience. Thank you for your time.",
	"Good afternoon, this is James Green. Im writing to you today to complain about your customer service. Ive been trying to get in touch with a representative for the past week, but I havent been able to get through. Im very disappointed with the way Ive been treated. I would like to speak to a manager. Please contact me at your earliest convenience. Thank you for your time.",
	"Good evening, this is Emily Thomas. Im writing to you today to offer a suggestion. I think you should add a new feature to your product. I think this feature would be very beneficial to your customers. Please consider my suggestion. Thank you for your time.",
	"Hi, this is William Anderson. Im writing to you today to congratulate you on your recent success. Im very impressed with the way your company has grown. I wish you continued success in the future. Thank you for your time.",
	"Hello, this is Jessica Clark. Im writing to you today to introduce myself. Im a new customer and Im very impressed with your company. Im looking forward to doing business with you in the future. Thank you for your time.",
	"Good morning, this is Robert Taylor. Im writing to you today to ask for your help. Im starting a new business and Im looking for advice. I would appreciate it if you could meet with me to discuss my business plan. Please contact me at your earliest convenience. Thank you for your time.",
	"Good afternoon, this is Jennifer Wilson. Im writing to you today to ask for your support. Im running for office and I need your help to get elected. I would appreciate it if you could vote for me and help me spread the word about my campaign. Thank you for your time.",
	"Good evening, this is Richard Martin. Im writing to you today to say thank you. Im very grateful for your support. I",
	"I saw a flying elephant yesterday.",
	"The moon is made of cheese.",
	"I can talk to animals.",
	"I won the lottery last week.",
	"Im the Queen of England.",
}

var fakeAction = []string{
	"Create a new account",
	"Login to an account",
	"Logout of an account",
	"Search for something",
	"View a product page",
	"Add a product to cart",
	"Remove a product from cart",
	"Checkout with a product",
	"Cancel a checkout",
	"Leave a review",
	"Contact customer support",
	"Change password",
	"Update profile",
	"Delete account",
	"View order history",
	"Track an order",
	"Refund an order",
	"Dispute an order",
	"Report a problem",
	"Give feedback",
	"Share a link",
	"Follow a user",
	"Unfollow a user",
	"Block a user",
	"Unblock a user",
	"Create a new post",
	"Share a post",
	"Comment on a post",
	"Like a post",
	"Unlike a post",
	"Delete a post",
	"Pin a post",
	"Unpin a post",
	"Create a new group",
	"Join a group",
	"Leave a group",
	"Post in a group",
	"Comment on a group post",
	"Like a group post",
	"Unlike a group post",
	"Delete a group post",
	"Pin a group post",
	"Unpin a group post",
	"Create a new event",
	"Join an event",
	"Leave an event",
	"RSVP to an event",
	"Cancel an RSVP",
	"View event details",
	"Share event details",
	"Comment on an event",
	"Like an event",
	"Unlike an event",
	"Delete an event",
	"Pin an event",
	"Unpin an event",
	"Create a new chat room",
	"Join a chat room",
	"Leave a chat room",
	"Send a message in a chat room",
	"Receive a message in a chat room",
	"Delete a message in a chat room",
	"Pin a message in a chat room",
	"Unpin a message in a chat room",
	"Create a new file",
	"Upload a file",
	"Download a file",
	"Share a file",
	"Delete a file",
	"Rename a file",
	"Move a file",
	"Copy a file",
	"Encrypt a file",
	"Decrypt a file",
	"Sign a file",
	"Verify a signature",
	"Watermark a file",
	"Remove a watermark",
}

var listOfControllers = []string{"Blog", "Route", "Place", "State", "Comment", "Like", "User", "Path", "TravelGuisde", "Notifications", "Logs"}
var listOfFunctions = []string{"Index", "Edit", "Update", "Show", "ShowAll", "Destroy", "get_user_input", "check_password", "validate_email", "format_date", "generate_random_number", "sort_list", "find_duplicates", "remove_duplicates", "count_words", "reverse_string", "encrypt_message", "decrypt_message", "compress_file", "decompress_file", "upload_file", "download_file", "create_folder", "delete_folder", "list_files", "open_file", "close_file", "read_file", "write_file", "append_to_file", "delete_file", "create_database", "drop_database", "create_table", "drop_table", "insert_row", "update_row", "delete_row", "select_row", "select_all_rows", "join_tables", "group_by", "order_by", "limit", "offset"}
var listOfResults = []string{"OK", "Created", "Accepted", "Non-Authoritative Information", "No Content", "Reset Content", "Partial Content", "Multiple Choices", "Moved Permanently", "Found", "See Other", "Not Modified", "Use Proxy", "Temporary Redirect", "BadRequest", "Unauthorized", "Forbidden", "Not Found", "Method Not Allowed", "Not Acceptable", "Proxy Authentication Required", "Request Timeout"}
var listOfBrowser = []string{"Google Chrome", "Mozilla Firefox", "Opera", "Apple Safari", "Microsoft Edge", "Netscape", "", "Web Explorer", "Surf", "Surfy", "Browse", "Searcher", "Webster", "Searchalot", "Searcherific", "Searchtopia", "Searchville"}
var listOfOs = []string{"Windows", "Linux", "Apple", "IOS", "Android", "", "Astra", "Bliss", "CentOS", "Elementary OS", "Fedora", "GNOME", "Kubuntu", "Linux Mint", "openSUSE", "Pop!_OS"}
var listOfApp = []string{"Mobile v1.1", "Mobile v1.2", "Mobile v1.3", "Mobile v2.0", "Mobile v2.1", "Mobile v3.0", "Web"}
var listOfTable = []string{"User", "Profile", "Blogs", "Comments", "Likes", "Images", "Activities", "Routes", "States", "Places", "TravelGuides", "Paths", "Logs", "Emails", "Notifications", "Monitoring", "users", "products", "orders", "customers", "orders_products", "inventory", "shipping", "payments", "taxes", "promotions", "marketing", "analytics", "reports", "logs", "settings", "configuration", "backups", "restores", "test", "development"}
var listOfMicros = []string{"Blogs", "Gateway", "Authorization", "Routes", "GO", "ELK", "Jenkins", "GitLab", "MailHog", "Redis", "Postgres", "MySql", "UserService", "ProductService", "OrderService", "PaymentService", "ShippingService", "InventoryService", "CustomerService", "SupportService", "MarketingService", "SalesService", "AnalyticsService", "ReportingService", "DocumentationService", "AuditService", "ComplianceService", "SecurityService", "InfrastructureService", "OperationsService", "MonitoringService"}

var slugsList []string = []string{"Aaren", "Aarika", "Abagael", "Abagail", "Abbe", "Abbey", "Ronny", "Roobbie", "Rora", "Rori", "Rorie", "Rory", "Ros", "Rosa", "Rosabel", "Rosabella", "Rosabelle", "Rosaleen", "Rosalia", "Rosalie", "Rosalind", "Rosalinda", "Rosalinde", "Rosaline", "Rosalyn", "Rosalynd", "Rosamond", "Rosamund", "Rosana", "Rosanna", "Rosanne", "Rose", "Roseann", "Roseanna", "Roseanne", "Roselia", "Roselin", "Roseline", "Rosella", "Roselle", "Rosemaria", "Rosemarie", "Rosemary", "Rosemonde", "Rosene", "Rosetta", "Rosette", "Roshelle", "Rosie", "Rosina", "Rosita", "Roslyn", "Rosmunda", "Rosy", "Row", "Rowe", "Rowena", "Roxana", "Roxane", "Roxanna", "Roxanne", "Roxi", "Roxie", "Roxine", "Roxy", "Roz", "Rozalie", "Rozalin", "Rozamond", "Rozanna", "Rozanne", "Roze", "Rozele", "Rozella", "Rozelle", "Rozina", "Rubetta", "Rubi", "Rubia", "Rubie", "Rubina", "Ruby", "Ruperta", "Ruth", "Ruthann", "Ruthanne", "Ruthe", "Ruthi", "Ruthie", "Ruthy", "Ryann", "Rycca", "Saba", "Sabina", "Sabine", "Sabra", "Sabrina", "Sacha", "Sada", "Sadella", "Sadie", "Sadye", "Saidee", "Sal", "Salaidh", "Sallee", "Salli", "Sallie", "Sally", "Sallyann", "Sallyanne", "Saloma", "Salome", "Salomi", "Sam", "Samantha", "Samara", "Samaria", "Sammy", "Sande", "Sandi", "Sandie", "Sandra", "Sandy", "Sandye", "Sapphira", "Sapphire", "Sara", "Sara-Ann", "Saraann", "Sarah", "Sarajane", "Saree", "Sarena", "Sarene", "Sarette", "Sari", "Sarina", "Sarine", "Sarita", "Sascha", "Sasha", "Sashenka", "Saudra", "Saundra", "Savina", "Sayre", "Scarlet", "Scarlett", "Sean", "Seana", "Seka", "Sela", "Selena", "Selene", "Selestina", "Selia", "Selie", "Selina", "Selinda", "Seline", "Sella", "Selle", "Selma", "Sena", "Sephira", "Serena", "Serene", "Shae", "Shaina", "Shaine", "Shalna", "Shalne", "Shana", "Shanda", "Shandee", "Shandeigh", "Shandie", "Shandra", "Shandy", "Shane", "Shani", "Shanie", "Shanna", "Shannah", "Shannen", "Shannon", "Shanon", "Shanta", "Shantee", "Shara", "Sharai", "Shari", "Sharia", "Sharity", "Sharl", "Sharla", "Sharleen", "Sharlene", "Sharline", "Sharon", "Sharona", "Sharron", "Sharyl", "Shaun", "Shauna", "Shawn", "Shawna", "Shawnee", "Shay", "Shayla", "Shaylah", "Shaylyn", "Shaylynn", "Shayna", "Shayne", "Shea", "Sheba", "Sheela", "Sheelagh", "Sheelah", "Sheena", "Sheeree", "Sheila", "Sheila-Kathryn", "Sheilah", "Shel", "Shela", "Shelagh", "Shelba", "Shelbi", "Shelby", "Shelia", "Shell", "Shelley", "Shelli", "Shellie", "Shelly", "Shena", "Sher", "Sheree", "Sheri", "Sherie", "Sherill", "Sherilyn", "Sherline", "Sherri", "Sherrie", "Sherry", "Sherye", "Sheryl", "Shina", "Shir", "Shirl", "Shirlee", "Shirleen", "Shirlene", "Shirley", "Shirline", "Shoshana", "Shoshanna", "Siana", "Sianna", "Sib", "Sibbie", "Sibby", "Sibeal", "Sibel", "Sibella", "Sibelle", "Sibilla", "Sibley", "Sibyl", "Sibylla", "Sibylle", "Sidoney", "Sidonia", "Sidonnie", "Sigrid", "Sile", "Sileas", "Silva", "Silvana", "Silvia", "Silvie", "Simona", "Simone", "Simonette", "Simonne", "Sindee", "Siobhan", "Sioux", "Siouxie", "Sisely", "Sisile", "Sissie", "Sissy", "Siusan", "Sofia", "Sofie", "Sondra", "Sonia", "Sonja", "Sonni", "Sonnie", "Sonnnie", "Sonny", "Sonya", "Sophey", "Sophi", "Sophia", "Sophie", "Sophronia", "Sorcha", "Sosanna", "Stace", "Stacee", "Stacey", "Staci", "Stacia", "Stacie", "Stacy", "Stafani", "Star", "Starla", "Starlene", "Starlin", "Starr", "Stefa", "Stefania", "Stefanie", "Steffane", "Steffi", "Steffie", "Stella", "Stepha", "Stephana", "Stephani", "Stephanie", "Stephannie", "Stephenie", "Stephi", "Stephie", "Stephine", "Stesha", "Stevana", "Stevena", "Stoddard", "Storm", "Stormi", "Stormie", "Stormy", "Sue", "Suellen", "Sukey", "Suki", "Sula", "Sunny", "Sunshine", "Susan", "Susana", "Susanetta", "Susann", "Susanna", "Susannah", "Susanne", "Susette", "Susi", "Susie", "Susy", "Suzann", "Suzanna", "Suzanne", "Suzette", "Suzi", "Suzie", "Suzy", "Sybil", "Sybila", "Sybilla", "Sybille", "Sybyl", "Sydel", "Sydelle", "Sydney", "Sylvia", "Tabatha", "Tabbatha", "Tabbi", "Tabbie", "Tabbitha", "Tabby", "Tabina", "Tabitha", "Taffy", "Talia", "Tallia", "Tallie", "Tallou", "Tallulah", "Tally", "Talya", "Talyah", "Tamar", "Tamara", "Tamarah", "Tamarra", "Tamera", "Tami", "Tamiko", "Tamma", "Tammara", "Tammi", "Tammie", "Tammy", "Tamqrah", "Tamra", "Tana", "Tandi", "Tandie", "Tandy", "Tanhya", "Tani", "Tania", "Tanitansy", "Tansy", "Tanya", "Tara", "Tarah", "Tarra", "Tarrah", "Taryn", "Tasha", "Tasia", "Tate", "Tatiana", "Tatiania", "Tatum", "Tawnya", "Tawsha", "Ted", "Tedda", "Teddi", "Teddie", "Teddy", "Tedi", "Tedra", "Teena", "TEirtza", "Teodora", "Tera", "Teresa", "Terese", "Teresina", "Teresita", "Teressa", "Teri", "Teriann", "Terra", "Terri", "Terrie", "Terrijo", "Terry", "Terrye", "Tersina", "Terza", "Tess", "Tessa", "Tessi", "Tessie", "Tessy", "Thalia", "Thea", "Theadora", "Theda", "Thekla", "Thelma", "Theo", "Theodora", "Theodosia", "Theresa", "Therese", "Theresina", "Theresita", "Theressa", "Therine", "Thia", "Thomasa", "Thomasin", "Thomasina", "Thomasine", "Tiena", "Tierney", "Tiertza", "Tiff", "Tiffani", "Tiffanie", "Tiffany", "Tiffi", "Tiffie", "Tiffy", "Tilda", "Tildi", "Tildie", "Tildy", "Tillie", "Tilly", "Tim", "Timi", "Timmi", "Timmie", "Timmy", "Timothea", "Tina", "Tine", "Tiphani", "Tiphanie", "Tiphany", "Tish", "Tisha", "Tobe", "Tobey", "Tobi", "Toby", "Tobye", "Toinette", "Toma", "Tomasina", "Tomasine", "Tomi", "Tommi", "Tommie", "Tommy", "Toni", "Tonia", "Tonie", "Tony", "Tonya", "Tonye", "Tootsie", "Torey", "Tori", "Torie", "Torrie", "Tory", "Tova", "Tove", "Tracee", "Tracey", "Traci", "Tracie", "Tracy", "Trenna", "Tresa", "Trescha", "Tressa", "Tricia", "Trina", "Trish", "Trisha", "Trista", "Trix", "Trixi", "Trixie", "Trixy", "Truda", "Trude", "Trudey", "Trudi", "Trudie", "Trudy", "Trula", "Tuesday", "Twila", "Twyla", "Tybi", "Tybie", "Tyne", "Ula", "Ulla", "Ulrica", "Ulrika", "Ulrikaumeko", "Ulrike", "Umeko", "Una", "Ursa", "Ursala", "Ursola", "Ursula", "Ursulina", "Ursuline", "Uta", "Val", "Valaree", "Valaria", "Vale", "Valeda", "Valencia", "Valene", "Valenka", "Valentia", "Valentina", "Valentine", "Valera", "Valeria", "Valerie", "Valery", "Valerye", "Valida", "Valina", "Valli", "Vallie", "Vally", "Valma", "Valry", "Van", "Vanda", "Vanessa", "Vania", "Vanna", "Vanni", "Vannie", "Vanny", "Vanya", "Veda", "Velma", "Velvet", "Venita", "Venus", "Vera", "Veradis", "Vere", "Verena", "Verene", "Veriee", "Verile", "Verina", "Verine", "Verla", "Verna", "Vernice", "Veronica", "Veronika", "Veronike", "Veronique", "Vevay", "Vi", "Vicki", "Vickie", "Vicky", "Victoria", "Vida", "Viki", "Vikki", "Vikky", "Vilhelmina", "Vilma", "Vin", "Vina", "Vinita", "Vinni", "Vinnie", "Vinny", "Viola", "Violante", "Viole", "Violet", "Violetta", "Violette", "Virgie", "Virgina", "Virginia", "Virginie", "Vita", "Vitia", "Vitoria", "Vittoria", "Viv", "Viva", "Vivi", "Vivia", "Vivian", "Viviana", "Vivianna", "Vivianne", "Vivie", "Vivien", "Viviene", "Vivienne", "Viviyan", "Vivyan", "Vivyanne", "Vonni", "Vonnie", "Vonny", "Vyky", "Wallie", "Wallis", "Walliw", "Wally", "Waly", "Wanda", "Wandie", "Wandis", "Waneta", "Wanids", "Wenda", "Wendeline", "Wendi", "Wendie", "Wendy", "Wendye", "Wenona", "Wenonah", "Whitney", "Wileen", "Wilhelmina", "Wilhelmine", "Wilie", "Willa", "Willabella", "Willamina", "Willetta", "Willette", "Willi", "Willie", "Willow", "Willy", "Willyt", "Wilma", "Wilmette", "Wilona", "Wilone", "Wilow", "Windy", "Wini", "Winifred", "Winna", "Winnah", "Winne", "Winni", "Winnie", "Winnifred", "Winny", "Winona", "Winonah", "Wren", "Wrennie", "Wylma", "Wynn", "Wynne", "Wynnie", "Wynny", "Xaviera", "Xena", "Xenia", "Xylia", "Xylina", "Yalonda", "Yasmeen", "Yasmin", "Yelena", "Yetta", "Yettie", "Yetty", "Yevette", "Ynes", "Ynez", "Yoko", "Yolanda", "Yolande", "Yolane", "Yolanthe", "Yoshi", "Yoshiko", "Yovonnda", "Ysabel", "Yvette", "Yvonne", "Zabrina", "Zahara", "Zandra", "Zaneta", "Zara", "Zarah", "Zaria", "Zarla", "Zea", "Zelda", "Zelma", "Zena", "Zenia", "Zia", "Zilvia", "Zita", "Zitella", "Zoe", "Zola", "Zonda", "Zondra", "Zonnya", "Zora", "Zorah", "Zorana", "Zorina", "Zorine", "Zsa Zsa", "Zsazsa", "Zulema", "Zuzana"}
var contentList []string = []string{"You can now derive a schema from example CSV, JSON, or XML data.", "You can now generate your own custom data types using AI.", "You can now generate fields on any topic using AI", "Added support for XML attributes by naming fields starting with 2", "Added the ability to generate v5 UUIDs via a new uuid_v5(namespace, name) function in formulas", "Added the ability to force the quote character on custom file formats.", "Added Address Line 2 type.", "Added a ULID data type.", "Added airport data.", "You can now generate datasets using JSON and import them into other schemas using the Dataset Column type.", "Added support for InfluxDB", "Added the ability to import fields from a JSON schema or example JSON object.", "You can now create a dataset directly from a schema. You no longer need to download and reupload generated data to create a dataset!", "You can now stream data to an MQTT endpoint! Click More > Stream to MQTT Endpoint... to get started.", "Added types related to construction work.", "Added Etherium and Tezos types."}

func randomSlug() (res string) {
	return randomPickStr(slugsList)
}

func randomContent() (res string) {
	return randomPickStr(contentList)
}

// randomSample picks a random element from array arr
func randomPickStr(arr []string) string {

	return arr[rand.Intn(len(arr))]
}
